<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Crowd.Project.Domain\Crowd.Project.Domain.csproj" />
    <ProjectReference Include="..\Crowd.Project.Infrastructure\Crowd.Project.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\shared\building-blocks\Crowd.BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\..\shared\persistence\Crowd.BuildingBlocks.Persistence.csproj" />
    <ProjectReference Include="..\..\..\shared\auth\Crowd.BuildingBlocks.Auth.csproj" />
    <ProjectReference Include="..\..\..\shared\contracts\Crowd.Contracts.csproj" />
  </ItemGroup>

</Project>
