// <auto-generated />
using System;
using Crowd.Annotation.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Crowd.Annotation.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AnnotationDbContext))]
    partial class AnnotationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Crowd.Annotation.Domain.Annotations.LabelAnnotation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppealMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("appeal_message");

                    b.Property<DateTimeOffset?>("AppealResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("appeal_resolved_at");

                    b.Property<DateTimeOffset?>("AppealedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("appealed_at");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<bool?>("ConsensusAgrees")
                        .HasColumnType("boolean")
                        .HasColumnName("consensus_agrees");

                    b.Property<DateTimeOffset?>("ConsensusAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consensus_at");

                    b.Property<Guid?>("LabelerId")
                        .HasColumnType("uuid")
                        .HasColumnName("labeler_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reject_reason");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SampleContent")
                        .HasColumnType("jsonb")
                        .HasColumnName("sample_content");

                    b.Property<Guid>("SampleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sample_id");

                    b.Property<string>("SampleMetadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("sample_metadata");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("storage_key");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("_payloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("_payloadSchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("_payloadTaskType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("task_type");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId")
                        .IsUnique()
                        .HasDatabaseName("ux_annotations_assignment");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_annotations_appeals")
                        .HasFilter("status = 'Appealed'");

                    b.HasIndex("_payloadJson")
                        .HasDatabaseName("ix_annotations_payload");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("_payloadJson"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("_payloadJson"), new[] { "jsonb_path_ops" });

                    b.HasIndex("LabelerId", "SubmittedAt")
                        .HasDatabaseName("ix_annotations_labeler");

                    b.HasIndex("ProjectId", "SampleId")
                        .HasDatabaseName("ix_annotations_project_sample");

                    b.HasIndex("ProjectId", "Status")
                        .HasDatabaseName("ix_annotations_project_status");

                    b.ToTable("annotations", (string)null);
                });

            modelBuilder.Entity("Crowd.Annotation.Domain.Annotations.TaskConsensus", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("Final")
                        .HasColumnType("jsonb")
                        .HasColumnName("final");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("SampleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sample_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("TaskId");

                    b.HasIndex("ProjectId", "SampleId")
                        .HasDatabaseName("ix_task_consensus_project_sample");

                    b.ToTable("task_consensus", (string)null);
                });

            modelBuilder.Entity("Crowd.Annotation.Domain.Members.MemberCache", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ProjectId", "UserId");

                    b.ToTable("project_members_cache", (string)null);
                });

            modelBuilder.Entity("Crowd.Annotation.Domain.Projects.ProjectTerms", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_final");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("modality");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<long>("PlatformFeeVnd")
                        .HasColumnType("bigint")
                        .HasColumnName("platform_fee_vnd");

                    b.Property<long>("UnitPriceVnd")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_price_vnd");

                    b.Property<string>("_labelSchemaJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("label_schema");

                    b.HasKey("ProjectId");

                    b.ToTable("project_terms", (string)null);
                });

            modelBuilder.Entity("Crowd.BuildingBlocks.Persistence.Idempotency.ProcessedEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Handler")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("handler");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("EventId", "Handler")
                        .HasName("PK_processed_events");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_processed_events_thoi_diem");

                    b.ToTable("processed_events", (string)null);
                });

            modelBuilder.Entity("Crowd.BuildingBlocks.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EnvelopeJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("envelope_json");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("NextAttemptAt")
                        .HasDatabaseName("ix_outbox_cho_gui")
                        .HasFilter("published_at IS NULL");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("ix_outbox_da_gui")
                        .HasFilter("published_at IS NOT NULL");

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("Crowd.Settings.SettingReplica", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Key");

                    b.ToTable("settings_replica", (string)null);
                });

            modelBuilder.Entity("Crowd.Annotation.Domain.Annotations.LabelAnnotation", b =>
                {
                    b.OwnsMany("Crowd.Annotation.Domain.Annotations.AnnotationHistoryEntry", "History", b1 =>
                        {
                            b1.Property<long>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b1.Property<long>("id"));

                            b1.Property<string>("Action")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("action");

                            b1.Property<Guid?>("ActorId")
                                .HasColumnType("uuid")
                                .HasColumnName("actor_id");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("at");

                            b1.Property<string>("Note")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("note");

                            b1.Property<Guid>("annotation_id")
                                .HasColumnType("uuid");

                            b1.HasKey("id");

                            b1.HasIndex("annotation_id");

                            b1.ToTable("annotation_history", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("annotation_id");
                        });

                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
