// <auto-generated />
using System;
using Crowd.Tasking.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Crowd.Tasking.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TaskDbContext))]
    [Migration("20261010054601_AutovacuumHangDoiTask")]
    partial class AutovacuumHangDoiTask
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Crowd.BuildingBlocks.Persistence.Idempotency.ProcessedEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Handler")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("handler");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("EventId", "Handler")
                        .HasName("PK_processed_events");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_processed_events_thoi_diem");

                    b.ToTable("processed_events", (string)null);
                });

            modelBuilder.Entity("Crowd.BuildingBlocks.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EnvelopeJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("envelope_json");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("NextAttemptAt")
                        .HasDatabaseName("ix_outbox_cho_gui")
                        .HasFilter("published_at IS NULL");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("ix_outbox_da_gui")
                        .HasFilter("published_at IS NOT NULL");

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("Crowd.Settings.SettingReplica", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Key");

                    b.ToTable("settings_replica", (string)null);
                });

            modelBuilder.Entity("Crowd.Tasking.Domain.Assignments.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsGold")
                        .HasColumnType("boolean")
                        .HasColumnName("is_gold");

                    b.Property<Guid>("LabelerId")
                        .HasColumnType("uuid")
                        .HasColumnName("labeler_id");

                    b.Property<DateTimeOffset>("LeasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("leased_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("SampleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sample_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("_payloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int?>("_payloadSchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("_payloadTaskType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("task_type");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_assignments_reaper")
                        .HasFilter("state = 'Leased'");

                    b.HasIndex("LabelerId", "TaskId")
                        .HasDatabaseName("ix_assignments_labeler_active")
                        .HasFilter("state IN ('Leased','Submitted')");

                    b.HasIndex("ProjectId", "LabelerId")
                        .IsUnique()
                        .HasDatabaseName("ux_assignments_one_lease_per_project")
                        .HasFilter("state = 'Leased'");

                    b.HasIndex("TaskId", "LabelerId")
                        .IsUnique()
                        .HasDatabaseName("ux_assignments_task_labeler_active")
                        .HasFilter("state IN ('Leased','Submitted')");

                    b.ToTable("assignments", null, t =>
                        {
                            t.HasCheckConstraint("ck_assignments_payload", "(task_type IS NULL) = (payload IS NULL) AND (schema_version IS NULL) = (payload IS NULL) AND (state = 'Submitted') = (payload IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Crowd.Tasking.Domain.Labelers.LabelerProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("Blocked")
                        .HasColumnType("boolean")
                        .HasColumnName("blocked");

                    b.Property<DateTimeOffset>("BlockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blocked_at");

                    b.Property<int?>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<DateTimeOffset>("LevelAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("level_at");

                    b.Property<int?>("Reputation")
                        .HasColumnType("integer")
                        .HasColumnName("reputation");

                    b.Property<DateTimeOffset>("ReputationAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reputation_at");

                    b.HasKey("UserId");

                    b.ToTable("labeler_cache", (string)null);
                });

            modelBuilder.Entity("Crowd.Tasking.Domain.Members.MemberCache", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ProjectId", "UserId");

                    b.ToTable("project_members_cache", (string)null);
                });

            modelBuilder.Entity("Crowd.Tasking.Domain.Projects.ProjectSnapshot", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<bool>("AllowProfessional")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_professional");

                    b.Property<DateTimeOffset?>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<int>("GoldCheckPercent")
                        .HasColumnType("integer")
                        .HasColumnName("gold_check_percent");

                    b.Property<DateTimeOffset>("GoldSetAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gold_set_at");

                    b.Property<bool>("IsConfigured")
                        .HasColumnType("boolean")
                        .HasColumnName("is_configured");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<int>("MaxRedundancy")
                        .HasColumnType("integer")
                        .HasColumnName("max_redundancy");

                    b.Property<int?>("MinLevel")
                        .HasColumnType("integer")
                        .HasColumnName("min_level");

                    b.Property<int?>("MinReputation")
                        .HasColumnType("integer")
                        .HasColumnName("min_reputation");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("modality");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("Redundancy")
                        .HasColumnType("integer")
                        .HasColumnName("redundancy");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_changed_at");

                    b.Property<long>("UnitPriceVnd")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_price_vnd");

                    b.Property<string>("_labelSchemaJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("label_schema");

                    b.HasKey("ProjectId");

                    b.ToTable("project_snapshots", (string)null);
                });

            modelBuilder.Entity("Crowd.Tasking.Domain.Tasks.GoldSample", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("SampleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sample_id");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("purpose");

                    b.Property<string>("_expectedPayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("expected_payload");

                    b.Property<int>("_expectedSchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("expected_schema_version");

                    b.Property<string>("_expectedTaskType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("expected_task_type");

                    b.HasKey("ProjectId", "SampleId");

                    b.ToTable("gold_samples", (string)null);
                });

            modelBuilder.Entity("Crowd.Tasking.Domain.Tasks.LabelingTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActiveLeaseCount")
                        .HasColumnType("integer")
                        .HasColumnName("active_lease_count");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Content")
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("modality");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("RedundancyTarget")
                        .HasColumnType("integer")
                        .HasColumnName("redundancy_target");

                    b.Property<Guid>("SampleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sample_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("storage_key");

                    b.Property<int>("SubmittedCount")
                        .HasColumnType("integer")
                        .HasColumnName("submitted_count");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "SampleId")
                        .IsUnique()
                        .HasDatabaseName("ux_tasks_project_sample");

                    b.HasIndex("ProjectId", "State", "Id")
                        .HasDatabaseName("ix_tasks_pool");

                    b.ToTable("tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_tasks_file_hoac_noi_dung", "(storage_key IS NULL) <> (content IS NULL)");
                        });
                });

            modelBuilder.Entity("Crowd.Tasking.Domain.Assignments.Assignment", b =>
                {
                    b.HasOne("Crowd.Tasking.Domain.Tasks.LabelingTask", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
