<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Crowd.Payment.Domain\Crowd.Payment.Domain.csproj" />
    <ProjectReference Include="..\Crowd.Payment.Infrastructure\Crowd.Payment.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\shared\building-blocks\Crowd.BuildingBlocks.csproj" />
  </ItemGroup>

</Project>
