<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Crowd.Ledger.Domain\Crowd.Ledger.Domain.csproj" />
    <ProjectReference Include="..\Crowd.Ledger.Infrastructure\Crowd.Ledger.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\shared\building-blocks\Crowd.BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\..\shared\persistence\Crowd.BuildingBlocks.Persistence.csproj" />
    <ProjectReference Include="..\..\..\shared\auth\Crowd.BuildingBlocks.Auth.csproj" />
    <ProjectReference Include="..\..\..\shared\contracts\Crowd.Contracts.csproj" />
    <ProjectReference Include="..\..\..\shared\seeding\Crowd.Seeding.csproj" />
  </ItemGroup>

</Project>
